import { useEffect, useMemo, useState } from "react";
import {
  ArrowRight, ArrowUp, Building2, Check, ChevronRight, Clock3, Facebook, Flower2,
  HeartHandshake, Instagram, Leaf, Mail, MapPin, Menu, MessageCircle, Phone, Search,
  Seedling, Sprout, Store, Users, X, ZoomIn,
} from "lucide-react";
import { toast } from "sonner";
import { Button } from "@/components/ui/button";
import { articles, business, categories, gallery, products, type Product } from "@/data/nursery";
import heroImage from "@/assets/agroc-hero.jpg";
import storyImage from "@/assets/agroc-story.jpg";
import landscapeImage from "@/assets/agroc-landscape.jpg";

const links = [
  ["Home", "home"], ["Plants", "plants"], ["Agro Products", "categories"],
  ["About", "about"], ["Plant Care", "care"], ["Contact", "contact"],
] as const;

function waLink(message: string) {
  return `https://wa.me/${business.whatsappNumber}?text=${encodeURIComponent(message)}`;
}
function goTo(id: string) { document.getElementById(id)?.scrollIntoView({ behavior: "smooth" }); }

function Brand({ inverse = false }: { inverse?: boolean }) {
  return <a href="#home" className={`flex items-center gap-2 font-display text-2xl font-semibold ${inverse ? "text-cream" : "text-forest"}`} aria-label="Agroc home"><span className={`grid size-9 place-items-center rounded-full ${inverse ? "bg-cream text-forest" : "bg-primary text-primary-foreground"}`}><Leaf className="size-5" /></span>Agroc</a>;
}

function Header() {
  const [open, setOpen] = useState(false); const [compact, setCompact] = useState(false);
  useEffect(() => { const onScroll = () => setCompact(window.scrollY > 30); onScroll(); window.addEventListener("scroll", onScroll); return () => window.removeEventListener("scroll", onScroll); }, []);
  return <header className={`fixed inset-x-0 top-0 z-50 border-b border-transparent transition-all ${compact || open ? "bg-background/95 shadow-sm backdrop-blur-md !border-border" : "bg-background/90 backdrop-blur-sm"}`}>
    <div className={`mx-auto grid max-w-7xl grid-cols-[minmax(0,1fr)_auto] items-center px-4 transition-all sm:px-6 lg:px-8 ${compact ? "h-16" : "h-20"}`}>
      <Brand />
      <nav className="hidden items-center gap-6 lg:flex" aria-label="Primary navigation">{links.map(([label,id]) => <a key={id} href={`#${id}`} className="text-sm font-medium text-foreground/75 transition-colors hover:text-primary">{label}</a>)}<Button variant="whatsapp" asChild><a href={waLink("Hello, I found your nursery website and would like to know more about your plants and agricultural products.")} target="_blank" rel="noreferrer"><MessageCircle /> WhatsApp Us</a></Button></nav>
      <Button variant="ghost" size="icon" className="lg:hidden" onClick={() => setOpen(v => !v)} aria-label={open ? "Close menu" : "Open menu"}>{open ? <X /> : <Menu />}</Button>
    </div>
    {open && <nav className="border-t border-border bg-background px-4 py-4 lg:hidden" aria-label="Mobile navigation">{links.map(([label,id]) => <a key={id} href={`#${id}`} onClick={() => setOpen(false)} className="block border-b border-border/60 py-3 text-base font-medium">{label}</a>)}<Button variant="whatsapp" className="mt-4 w-full" size="lg" asChild><a href={waLink("Hello, I found your nursery website and would like to know more about your plants and agricultural products.")} target="_blank" rel="noreferrer"><MessageCircle /> WhatsApp Us</a></Button></nav>}
  </header>;
}

function SectionHeading({ eyebrow, title, text, light = false, align = "left" }: { eyebrow?: string; title: string; text?: string; light?: boolean; align?: "left" | "center" }) {
  return <div className={`mb-10 ${align === "center" ? "mx-auto max-w-2xl text-center" : "max-w-2xl"}`}>
    {eyebrow && <p className={`mb-3 text-xs font-bold uppercase tracking-[0.18em] ${light ? "text-leaf" : "text-primary"}`}>{eyebrow}</p>}
    <h2 className={`font-display text-4xl font-semibold leading-tight sm:text-5xl ${light ? "text-cream" : "text-foreground"}`}>{title}</h2>
    {text && <p className={`mt-4 leading-relaxed ${light ? "text-cream/75" : "text-muted-foreground"}`}>{text}</p>}
  </div>;
}

function Hero() { return <section id="home" className="relative min-h-[760px] overflow-hidden pt-20 sm:min-h-[800px]">
  <img src={heroImage} alt="A sunlit tropical plant nursery filled with fruit plants and flowers" width={1920} height={1280} className="absolute inset-0 h-full w-full object-cover" fetchPriority="high" />
  <div className="absolute inset-0 bg-hero-overlay" />
  <div className="relative mx-auto flex min-h-[680px] max-w-7xl items-center px-4 py-16 sm:min-h-[720px] sm:px-6 lg:px-8">
    <div className="max-w-3xl text-cream">
      <div className="mb-6 inline-flex items-center gap-2 border-l-2 border-leaf pl-3 text-sm font-semibold uppercase tracking-[0.14em]"><Sprout className="size-4" /> Plants for every space</div>
      <h1 className="font-display text-5xl font-semibold leading-[1.02] sm:text-7xl lg:text-8xl">Grow Something<br/><em className="font-normal text-leaf">Beautiful.</em></h1>
      <p className="mt-7 max-w-2xl text-lg font-medium leading-relaxed text-cream/95 sm:text-xl">Quality plants, gardening essentials and agricultural products for homes, gardens and farms.</p>
      <p className="mt-3 max-w-xl text-sm leading-relaxed text-cream/75 sm:text-base">Explore our collection, discover the right plants for your space, and get expert guidance from our nursery.</p>
      <div className="mt-8 flex flex-col gap-3 sm:flex-row"><Button size="xl" variant="cream" onClick={() => goTo("plants")}>Explore Plants <ArrowRight /></Button><Button size="xl" variant="heroOutline" asChild><a href={waLink("Hello, I found your nursery website and would like to know more about your plants and agricultural products.")} target="_blank" rel="noreferrer"><MessageCircle /> Chat on WhatsApp</a></Button></div>
      <p className="mt-6 text-sm text-cream/70">Local nursery <span className="mx-2 text-leaf">•</span> Quality plants <span className="mx-2 text-leaf">•</span> Personal guidance <span className="ml-2 text-xs">(editable positioning)</span></p>
    </div>
    <button onClick={() => goTo("contact")} className="absolute bottom-7 right-4 hidden w-60 border border-cream/30 bg-forest/80 p-5 text-left text-cream backdrop-blur-md transition hover:bg-forest sm:block lg:right-8" aria-label="View nursery location"><MapPin className="mb-5 size-6 text-leaf"/><span className="block font-display text-xl">Visit our Nursery</span><span className="mt-1 flex items-center gap-1 text-sm text-cream/70">View location <ArrowRight className="size-3" /></span></button>
  </div>
</section> }

function Categories({ onFilter }: { onFilter: (filter:string) => void }) { return <section id="categories" className="section-shell bg-background"><SectionHeading eyebrow="Browse the nursery" title="Find What You’re Looking For" text="From home gardening to agricultural needs, explore our collection." />
  <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{categories.map(c => <button key={c.name} onClick={() => { onFilter(c.filter); goTo("plants"); }} className="group relative aspect-[4/3] overflow-hidden rounded-card text-left shadow-soft"><img src={c.image} alt={c.name} width={1536} height={1024} loading="lazy" className="h-full w-full object-cover transition duration-500 group-hover:scale-105"/><span className="absolute inset-0 bg-card-overlay"/><span className="absolute inset-x-0 bottom-0 p-5 text-cream"><span className="flex items-end justify-between gap-3"><span><span className="font-display text-2xl font-semibold">{c.name}</span><span className="mt-1 block max-w-xs text-sm text-cream/75">{c.description}</span></span><span className="grid size-10 shrink-0 place-items-center rounded-full border border-cream/40 transition group-hover:bg-cream group-hover:text-forest"><ArrowRight className="size-4"/></span></span></span></button>)}</div>
</section> }

function ProductCard({ product }: { product: Product }) { const ask = () => toast.success(`Opening an enquiry for ${product.name}`); return <article className="group overflow-hidden rounded-card border border-border bg-card shadow-soft transition hover:-translate-y-1 hover:shadow-elevated">
  <div className="relative aspect-[4/3] overflow-hidden"><img src={product.image} alt={product.name} width={1536} height={1024} loading="lazy" className="h-full w-full object-cover transition duration-500 group-hover:scale-105"/><span className={`absolute left-3 top-3 rounded-full px-3 py-1 text-xs font-bold ${product.status.startsWith("Limited") ? "bg-warning text-warning-foreground" : "bg-success text-success-foreground"}`}>{product.status}</span></div>
  <div className="p-5"><p className="text-xs font-bold uppercase tracking-[0.14em] text-primary">{product.category}</p><h3 className="mt-2 font-display text-2xl font-semibold">{product.name}</h3><p className="mt-2 min-h-12 text-sm leading-relaxed text-muted-foreground">{product.description}</p><div className="mt-5 flex items-center justify-between border-t border-border pt-4"><span className="font-semibold text-foreground">{product.price}</span><Button size="sm" variant="whatsapp" asChild onClick={ask}><a href={waLink(`Hello, I’m interested in the ${product.name}. Could you please provide more details and current availability?`)} target="_blank" rel="noreferrer"><MessageCircle/> Ask</a></Button></div></div>
</article> }

const filterOptions = ["All", "Fruit", "Flowers", "Indoor", "Outdoor", "Vegetable", "Agro"];
function Products({ selected, onSelect }: { selected:string; onSelect:(v:string)=>void }) { const visible = selected === "All" || selected === "Agro" || selected === "Vegetable" ? (selected === "All" ? products : []) : products.filter(p => selected === "Fruit" ? p.tags.includes("Fruit") : selected === "Flowers" ? p.tags.includes("Flowers") : p.places.includes(selected)); return <section id="plants" className="section-shell bg-surface">
  <div className="flex flex-col justify-between gap-7 lg:flex-row lg:items-end"><SectionHeading eyebrow="Demo product catalogue" title="Popular Plants" text="A glimpse of the plants you could showcase on your online nursery."/><div className="mb-10 flex gap-2 overflow-x-auto pb-2">{filterOptions.map(f => <Button key={f} size="sm" variant={selected===f ? "default" : "outline"} onClick={() => onSelect(f)}>{f}</Button>)}</div></div>
  {visible.length ? <div className="grid gap-5 sm:grid-cols-2 lg:grid-cols-3">{visible.map(p => <ProductCard key={p.name} product={p}/>)}</div> : <div className="rounded-card border border-dashed border-primary/30 bg-background px-6 py-14 text-center"><Seedling className="mx-auto size-10 text-primary"/><h3 className="mt-4 font-display text-2xl font-semibold">Catalogue ready to grow</h3><p className="mx-auto mt-2 max-w-md text-muted-foreground">Add the client’s {selected.toLowerCase()} items here when the real catalogue is available.</p></div>}
  <p className="mt-6 text-center text-xs text-muted-foreground">Demo products, prices and availability — replace with confirmed business information.</p>
</section> }

function PlantFinder() { const [place,setPlace]=useState(""); const [need,setNeed]=useState(""); const [space,setSpace]=useState(""); const results=useMemo(()=>products.filter(p=>(!place||p.places.includes(place))&&(!need||p.tags.includes(need))&&(!space||p.spaces.includes(space))),[place,need,space]); const groups=[{label:"Where will you grow it?",values:["Indoor","Outdoor","Garden","Farm"],value:place,set:setPlace},{label:"What are you looking for?",values:["Fruit","Flowers","Decoration","Food / Vegetable","Low Maintenance"],value:need,set:setNeed},{label:"Space",values:["Small","Medium","Large"],value:space,set:setSpace}]; return <section className="section-shell bg-forest text-cream"><SectionHeading eyebrow="Plant finder" title="Looking for the Right Plant?" text="Not sure what suits your space? Start with a few simple choices." light/>
  <div className="grid gap-8 lg:grid-cols-[.9fr_1.1fr]"><div className="space-y-7">{groups.map(g=><fieldset key={g.label}><legend className="mb-3 text-sm font-semibold">{g.label}</legend><div className="flex flex-wrap gap-2">{g.values.map(v=><Button key={v} variant={g.value===v?"cream":"heroOutline"} size="sm" onClick={()=>g.set(g.value===v?"":v)}>{g.value===v&&<Check/>}{v}</Button>)}</div></fieldset>)}</div><div className="rounded-card bg-cream p-5 text-foreground"><div className="mb-4 flex items-center justify-between"><h3 className="font-display text-2xl font-semibold">Suggested for you</h3><span className="text-sm text-muted-foreground">{results.length} matches</span></div><div className="space-y-3">{results.slice(0,3).map(p=><div key={p.name} className="grid grid-cols-[64px_minmax(0,1fr)_auto] items-center gap-3 border-b border-border pb-3 last:border-0"><img src={p.image} alt="" width={96} height={96} loading="lazy" className="size-16 rounded-md object-cover"/><div className="min-w-0"><p className="truncate font-semibold">{p.name}</p><p className="truncate text-xs text-muted-foreground">{p.category} · {p.price}</p></div><Button size="icon" variant="ghost" asChild><a href={waLink(`Hello, I’m interested in the ${p.name}. Could you please provide more details and current availability?`)} target="_blank" rel="noreferrer" aria-label={`Ask about ${p.name}`}><MessageCircle/></a></Button></div>)}{!results.length&&<p className="py-12 text-center text-muted-foreground">Try another combination to see demo matches.</p>}</div></div></div>
</section> }

function Values() { const items=[[Seedling,"Healthy Plant Selection","Choose from carefully presented plant varieties."],[HeartHandshake,"Guidance for Beginners","Make better plant choices with simple care information."],[MessageCircle,"Easy Enquiries","Ask about availability directly through WhatsApp."],[MapPin,"Local & Convenient","Find the nursery, explore products and contact the team easily."]] as const; return <section className="section-shell bg-background"><SectionHeading eyebrow="A simpler nursery experience" title="Why Customers Choose Us" align="center"/><div className="grid gap-px overflow-hidden rounded-card border border-border bg-border sm:grid-cols-2 lg:grid-cols-4">{items.map(([Icon,title,text])=><div key={title} className="bg-background p-7"><Icon className="size-7 text-primary"/><h3 className="mt-5 font-display text-xl font-semibold">{title}</h3><p className="mt-2 text-sm leading-relaxed text-muted-foreground">{text}</p></div>)}</div></section> }

function Story() { return <section id="about" className="bg-surface"><div className="mx-auto grid max-w-7xl lg:grid-cols-2"><div className="min-h-[420px]"><img src={storyImage} alt="Nursery worker potting a young fruit plant" width={1536} height={1024} loading="lazy" className="h-full w-full object-cover"/></div><div className="flex items-center px-5 py-14 sm:px-10 lg:px-16"><div><p className="mb-3 text-xs font-bold uppercase tracking-[0.18em] text-primary">A nursery with purpose</p><h2 className="font-display text-4xl font-semibold leading-tight sm:text-5xl">More Than Plants —<br/>We Help You Grow.</h2><p className="mt-6 leading-relaxed text-muted-foreground">A modern online presence can make it easier for customers to discover your nursery, explore your products and contact you before they visit.</p><p className="mt-4 leading-relaxed text-muted-foreground">Whether someone is looking for a fruit plant for their home garden, flowers for a new landscape, or agricultural products for their next project, the website should make the journey simple.</p><Button className="mt-7" size="lg" onClick={()=>goTo("contact")}>Learn About Our Nursery <ArrowRight/></Button></div></div></div></section> }

function Journey() { const steps=[[Search,"Discover","Customers find the nursery online."],[Sprout,"Explore","They browse plants and products."],[MessageCircle,"Enquire","They contact the business through WhatsApp."],[Store,"Visit or Order","They take the next step."]] as const; return <section className="section-shell bg-background"><SectionHeading eyebrow="A clear customer journey" title="Built Around Your Customers" text="A simple demonstration of how the website can support a customer from first search to their next step." align="center"/><div className="grid gap-8 md:grid-cols-4">{steps.map(([Icon,title,text],i)=><div key={title} className="relative text-center"><span className="mx-auto grid size-14 place-items-center rounded-full bg-primary text-primary-foreground"><Icon className="size-6"/></span><span className="mt-4 block text-xs font-bold text-primary">0{i+1}</span><h3 className="mt-1 font-display text-xl font-semibold">{title}</h3><p className="mt-2 text-sm text-muted-foreground">{text}</p>{i<3&&<ChevronRight className="absolute -right-5 top-4 hidden text-border md:block"/>}</div>)}</div></section> }

function Care() { return <section id="care" className="section-shell bg-surface"><SectionHeading eyebrow="Demo knowledge hub" title="Grow Better With Simple Advice" text="Useful gardening content can help customers learn, return and discover the right products."/><div className="grid gap-5 md:grid-cols-3">{articles.map(a=><article key={a.title} className="group overflow-hidden rounded-card bg-card shadow-soft"><div className="aspect-[16/10] overflow-hidden"><img src={a.image} alt={a.title} width={1536} height={1024} loading="lazy" className="h-full w-full object-cover transition duration-500 group-hover:scale-105"/></div><div className="p-5"><p className="text-xs font-bold uppercase tracking-[0.14em] text-primary">{a.category}</p><h3 className="mt-2 font-display text-2xl font-semibold leading-tight">{a.title}</h3><p className="mt-3 text-sm leading-relaxed text-muted-foreground">{a.preview}</p><button className="mt-5 inline-flex items-center gap-2 text-sm font-bold text-primary" onClick={()=>toast.info("Demo article — full content can be added later")}>Read More <ArrowRight className="size-4"/></button></div></article>)}</div><p className="mt-5 text-center text-xs text-muted-foreground">Demo article previews for presentation purposes.</p></section> }

function Bulk() { return <section className="relative overflow-hidden py-24"><img src={landscapeImage} alt="Commercial tropical landscaping" width={1536} height={1024} loading="lazy" className="absolute inset-0 h-full w-full object-cover"/><div className="absolute inset-0 bg-bulk-overlay"/><div className="relative mx-auto max-w-7xl px-4 sm:px-6 lg:px-8"><div className="max-w-2xl text-cream"><p className="mb-3 text-xs font-bold uppercase tracking-[0.18em] text-leaf">For business & larger orders</p><h2 className="font-display text-4xl font-semibold sm:text-6xl">Planning a Larger Project?</h2><p className="mt-5 text-lg leading-relaxed text-cream/80">Looking for plants or agricultural products for a farm, landscaping project, office, hotel or other business?</p><div className="mt-8 flex flex-col gap-3 sm:flex-row"><Button variant="cream" size="xl" onClick={()=>{goTo("contact");toast.success("Quote request details are ready below")}}><Building2/> Request a Quote</Button><Button variant="heroOutline" size="xl" asChild><a href={waLink("Hello, I would like to discuss plants or agricultural products for a larger project.")} target="_blank" rel="noreferrer"><MessageCircle/> WhatsApp the Team</a></Button></div></div></div></section> }

function Gallery() { const [active,setActive]=useState<number|null>(null); return <section className="section-shell bg-background"><SectionHeading eyebrow="Inside the nursery" title="A Closer Look" text="A visual collection ready to be replaced with the nursery’s real photos."/><div className="grid auto-rows-[190px] grid-cols-2 gap-3 md:grid-cols-4">{gallery.map((g,i)=><button key={`${g.label}-${i}`} onClick={()=>setActive(i)} className={`group relative overflow-hidden rounded-card text-left ${i===0||i===5?"row-span-2":i===1?"md:col-span-2":""}`}><img src={g.image} alt={g.label} width={1536} height={1024} loading="lazy" className="h-full w-full object-cover transition duration-500 group-hover:scale-105"/><span className="absolute inset-0 bg-gallery-overlay opacity-50 transition group-hover:opacity-80"/><span className="absolute inset-x-0 bottom-0 flex items-center justify-between p-4 text-sm font-semibold text-cream">{g.label}<ZoomIn className="size-4"/></span></button>)}</div><div className="mt-7 text-center"><Button variant="outline" onClick={()=>toast.info("More nursery photos can be added here")}>See More Photos <ArrowRight/></Button></div>
  {active!==null&&<div className="fixed inset-0 z-[70] grid place-items-center bg-modal p-4" role="dialog" aria-modal="true" aria-label={gallery[active].label} onClick={()=>setActive(null)}><Button variant="cream" size="icon" className="absolute right-4 top-4" onClick={()=>setActive(null)} aria-label="Close image"><X/></Button><img src={gallery[active].image} alt={gallery[active].label} width={1536} height={1024} className="max-h-[85vh] max-w-[92vw] rounded-card object-contain"/></div>}
</section> }

function Contact() { const details=[[Phone,"Phone",business.phone],[MessageCircle,"WhatsApp",business.phone],[Mail,"Email",business.email],[Clock3,"Opening Hours",business.hours]] as const; return <section id="contact" className="section-shell bg-surface"><div className="grid gap-12 lg:grid-cols-2 lg:items-center"><div><SectionHeading eyebrow="Contact & location" title="Visit Us or Talk to Us" text="Use the placeholders below to show the owner exactly where their confirmed business information will appear."/><div className="grid gap-3 sm:grid-cols-2">{details.map(([Icon,label,value])=><div key={label} className="flex gap-3 rounded-card border border-border bg-background p-4"><Icon className="mt-1 size-5 shrink-0 text-primary"/><div><p className="text-xs font-bold uppercase tracking-[0.12em] text-muted-foreground">{label}</p><p className="mt-1 font-semibold">{value}</p></div></div>)}</div><Button className="mt-6" variant="whatsapp" size="lg" asChild><a href={waLink("Hello, I found your nursery website and would like to know more about your plants and agricultural products.")} target="_blank" rel="noreferrer"><MessageCircle/> Start a WhatsApp Enquiry</a></Button></div><div className="relative min-h-[430px] overflow-hidden rounded-card bg-map p-7 shadow-soft"><div className="absolute inset-0 map-grid opacity-40"/><div className="relative flex h-full min-h-[376px] flex-col items-center justify-center text-center"><span className="grid size-16 place-items-center rounded-full bg-primary text-primary-foreground shadow-elevated"><MapPin className="size-7"/></span><h3 className="mt-5 font-display text-3xl font-semibold">Google Maps Location</h3><p className="mt-2 text-muted-foreground">{business.location} · Exact location editable</p><Button className="mt-6" variant="outline" onClick={()=>toast.info("Add the confirmed Google Maps link here")}>View on Google Maps <ArrowRight/></Button></div></div></div></section> }

function Footer() { return <footer className="bg-forest text-cream"><div className="mx-auto grid max-w-7xl gap-10 px-4 py-14 sm:grid-cols-2 sm:px-6 lg:grid-cols-4 lg:px-8"><div><Brand inverse/><p className="mt-5 max-w-xs text-sm leading-relaxed text-cream/65">{business.tagline}</p></div><div><h3 className="text-sm font-bold uppercase tracking-[0.12em]">Quick Links</h3><div className="mt-4 space-y-2">{links.map(([label,id])=><a key={id} href={`#${id}`} className="block text-sm text-cream/65 hover:text-leaf">{label}</a>)}</div></div><div><h3 className="text-sm font-bold uppercase tracking-[0.12em]">Contact</h3><div className="mt-4 space-y-3 text-sm text-cream/65"><p>{business.phone}</p><p>{business.email}</p><p>{business.location}</p></div></div><div><h3 className="text-sm font-bold uppercase tracking-[0.12em]">Follow Us</h3><div className="mt-4 flex gap-2"><Button variant="heroOutline" size="icon" aria-label="Facebook"><Facebook/></Button><Button variant="heroOutline" size="icon" aria-label="Instagram"><Instagram/></Button><Button variant="heroOutline" size="icon" aria-label="TikTok"><Users/></Button></div></div></div><div className="border-t border-cream/10"><div className="mx-auto flex max-w-7xl flex-col gap-2 px-4 py-5 text-xs text-cream/50 sm:flex-row sm:justify-between sm:px-6 lg:px-8"><p>© 2026 Agroc. All rights reserved.</p><p>Digital experience by <span className="text-cream/80">CZone</span></p></div></div></footer> }

export function AgrocHome() { const [filter,setFilter]=useState("All"); const [showTop,setShowTop]=useState(false); useEffect(()=>{const f=()=>setShowTop(window.scrollY>650);window.addEventListener("scroll",f);return()=>window.removeEventListener("scroll",f)},[]); return <div className="min-h-screen bg-background font-sans"><Header/><main><Hero/><Categories onFilter={setFilter}/><Products selected={filter} onSelect={setFilter}/><PlantFinder/><Values/><Story/><Journey/><Care/><Bulk/><Gallery/><Contact/></main><Footer/>
<a href={waLink("Hello, I found your nursery website and would like to know more about your plants and agricultural products.")} target="_blank" rel="noreferrer" className="fixed bottom-4 left-4 z-40 flex h-13 items-center gap-2 rounded-full bg-whatsapp px-4 text-sm font-bold text-whatsapp-foreground shadow-float transition hover:-translate-y-1 sm:bottom-6 sm:left-auto sm:right-6" aria-label="Chat with us on WhatsApp"><MessageCircle className="size-5"/> Chat with us</a>
{showTop&&<Button className="fixed bottom-4 right-4 z-40 sm:bottom-24 sm:right-6" size="icon" variant="secondary" onClick={()=>window.scrollTo({top:0,behavior:"smooth"})} aria-label="Back to top"><ArrowUp/></Button>}</div> }
